export const imageSources = [
  {
    src: "/assets/images/life/life1.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: true,
    alt: "Dzieci Hoodmood podczas wspólnego wyjazdu w centrum Helios",
  },
  {
    src: "/assets/images/life/life2.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Uczestnicy Hoodmood tworzą prace plastyczne podczas warsztatów",
  },
  {
    src: "/assets/images/life/life3.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Tancerki Hoodmood występują na plenerowej scenie przed publicznością",
  },
  {
    src: "/assets/images/life/life4.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Dzieci w strojach ochronnych podczas zabawy terenowej",
  },
  {
    src: "/assets/images/life/life5.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Uczestniczki Hoodmood płyną kajakiem podczas wspólnego wyjazdu",
  },
  {
    src: "/assets/images/life/life6.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Dzieci poznają zioła i naturalne materiały podczas warsztatów",
  },
  {
    src: "/assets/images/life/life7.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Dzieci i instruktorka Hoodmood uczestniczą w zajęciach kreatywnych",
  },
  {
    src: "/assets/images/life/life8.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Grupa Hoodmood po występie trzyma medale i pamiątkowe dyplomy",
  },
  {
    src: "/assets/images/life/life9.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Dzieci Hoodmood prezentują prace wykonane podczas zajęć",
  },
  {
    src: "/assets/images/life/life10.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Dziecko maluje napis na folii podczas plenerowych warsztatów",
  },
  {
    src: "/assets/images/life/life11.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Grupa Hoodmood świętuje przy wspólnym stole",
  },
  {
    src: "/assets/images/life/life12.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Uczestniczka Hoodmood gra w bilard podczas wyjazdu grupowego",
  },
  {
    src: "/assets/images/life/life13.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Dzieci pokazują kolorowe kolaże podczas zajęć w sali",
  },
  {
    src: "/assets/images/life/life14.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Uczestnicy spotkania Hoodmood podczas świątecznej imprezy",
  },
  {
    src: "/assets/images/life/life15.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Trójka uczestników Hoodmood w kaskach przed trasą parku linowego",
  },
  {
    src: "/assets/images/life/life16.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Grupa Hoodmood pozuje w lustrzanej kuli przed londyńskim Westminsterem",
  },
  {
    src: "/assets/images/life/life17.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Duże wydarzenie plenerowe z publicznością, sceną i występem",
  },
  {
    src: "/assets/images/life/life18.jpg",
    width: 400,
    height: 600,
    media: "(max-width: 640px)",
    sizes: "(max-width: 640px) calc(100vw - 2rem), 33vw",
    priority: false,
    alt: "Grupa Hoodmood na karuzeli w parku rozrywki",
  },
];
       