import type { Metadata } from "next";
import { Anton, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/myComponents/themeProvider/ThemeProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import Navbar from "@/myComponents/navbar/Navbar";
import Footer from "@/myComponents/footer/Footer";
import { PricingFiltersProvider } from "@/myComponents/pages/pricing/PricingFiltersProvider";
import NextTopLoader from "nextjs-toploader";

const fontAnton = Anton({
  variable: "--anton",
  subsets: ["latin-ext"],
  weight: "400",
  fallback: ["system-ui", "Segoe UI", "Arial"],
});

const fontRoboto = Roboto_Condensed({
  variable: "--roboto-condensed",
  subsets: ["latin-ext"],
  fallback: ["system-ui", "Segoe UI", "Arial"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" suppressHydrationWarning>
      <body
        className={`${fontAnton.variable} ${fontRoboto.variable} w-full relative bg-transparent`}
      >
        <div className="fixed inset-0 -z-40 overflow-hidden">
          <div className="absolute inset-0  bg-cover bg-center bg-no-repeat " />

          <video
            src="/assets/images/bgVideo.mp4"
            className="absolute inset-0 h-full w-full object-cover"
            autoPlay
            muted
            loop
            playsInline
            preload="auto"
          />

          {/* <div className="absolute inset-0 bg-white/70 dark:bg-black/30" /> */}
        </div>
        <NextTopLoader
          color="#ac4967"
          height={3}
          easing="ease"
          initialPosition={0.08}
          crawlSpeed={200}
          crawl={true}
          speed={200}
          showSpinner={false}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <TooltipProvider>
            <PricingFiltersProvider>
              <Navbar />
              {children}
              <Footer />
            </PricingFiltersProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
