import type { Metadata } from "next";
import { Anton, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/myComponents/themeProvider/ThemeProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import Navbar from "@/myComponents/navbar/Navbar";
import Footer from "@/myComponents/footer/Footer";
import { PricingFiltersProvider } from "@/myComponents/pages/pricing/PricingFiltersProvider";
import NextTopLoader from "nextjs-toploader";

const fontAnton = Anton({
  variable: "--anton",
  subsets: ["latin-ext"],
  weight: "400",
  fallback: ["system-ui", "Segoe UI", "Arial"],
});

const fontRoboto = Roboto_Condensed({
  variable: "--roboto-condensed",
  subsets: ["latin-ext"],
  fallback: ["system-ui", "Segoe UI", "Arial"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" suppressHydrationWarning>
      <body className={`${fontAnton.variable} ${fontRoboto.variable} w-full `}>
        <NextTopLoader
          color="#ac4967"
          height={3}
          easing="ease"
          initialPosition={0.08}
          crawlSpeed={200}
          crawl={true}
          speed={200}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <TooltipProvider>
            <PricingFiltersProvider>
              <Navbar />
              {children}
              <Footer />
            </PricingFiltersProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
