export const imageSources = [
  {
    src: "/assets/images/life/life1.jpg",
    alt: "Dzieci Hoodmood podczas wspólnego wyjazdu w centrum Helios",
    className: "col-span-6",
    sizes: "(min-width: 1520px) 696px, 50vw",
    revealDelay: 0,
  },
  {
    src: "/assets/images/life/life2.jpg",
    alt: "Uczestnicy Hoodmood tworzą prace plastyczne podczas warsztatów",
    className: "col-span-3",
    sizes: "(min-width: 1520px) 340px, 25vw",
    revealDelay: 200,
  },
  {
    src: "/assets/images/life/life3.jpg",
    alt: "Tancerki Hoodmood występują na plenerowej scenie przed publicznością",
    className: "col-span-3 md:aspect-square",
    sizes: "(min-width: 1520px) 340px, 25vw",
    revealDelay: 100,
  },
  {
    src: "/assets/images/life/life4.jpg",
    alt: "Dzieci w strojach ochronnych podczas zabawy terenowej",
    className: "col-span-2",
    sizes: "(min-width: 1520px) 220px, 17vw",
    revealDelay: 200,
  },
  {
    src: "/assets/images/life/life5.jpg",
    alt: "Uczestniczki Hoodmood płyną kajakiem podczas wspólnego wyjazdu",
    className: "col-span-2",
    sizes: "(min-width: 1520px) 220px, 17vw",
    revealDelay: 0,
  },
  {
    src: "/assets/images/life/life6.jpg",
    alt: "Dzieci poznają zioła i naturalne materiały podczas warsztatów",
    className: "col-span-2",
    sizes: "(min-width: 1520px) 220px, 17vw",
    revealDelay: 100,
  },
  {
    src: "/assets/images/life/life7.jpg",
    alt: "Dzieci i instruktorka Hoodmood uczestniczą w zajęciach kreatywnych",
    className: "col-span-6 md:aspect-5/2",
    sizes: "(min-width: 1520px) 696px, 50vw",
    revealDelay: 0,
  },
  {
    src: "/assets/images/life/life8.jpg",
    alt: "Grupa Hoodmood po występie trzyma medale i pamiątkowe dyplomy",
    className: "col-span-4 md:aspect-3/3",
    sizes: "(min-width: 1520px) 453px, 33vw",
    revealDelay: 0,
  },
  {
    src: "/assets/images/life/life9.jpg",
    alt: "Dzieci Hoodmood prezentują prace wykonane podczas zajęć",
    className: "col-span-4",
    sizes: "(min-width: 1520px) 453px, 33vw",
    revealDelay: 200,
  },
  {
    src: "/assets/images/life/life10.jpg",
    alt: "Dziecko maluje napis na folii podczas plenerowych warsztatów",
    className: "col-span-4",
    sizes: "(min-width: 1520px) 453px, 33vw",
    revealDelay: 100,
  },
  {
    src: "/assets/images/life/life11.jpg",
    alt: "Grupa Hoodmood świętuje przy wspólnym stole",
    className: "col-span-6 md:aspect-4/2",
    sizes: "(min-width: 1520px) 453px, 33vw",
    revealDelay: 200,
  },
  {
    src: "/assets/images/life/life12.jpg",
    alt: "Uczestniczka Hoodmood gra w bilard podczas wyjazdu grupowego",
    className: "col-span-6",
    sizes: "(min-width: 1520px) 453px, 33vw",
    revealDelay: 0,
  },
  {
    src: "/assets/images/life/life13.jpg",
    alt: "Dzieci pokazują kolorowe kolaże podczas zajęć w sali",
    className: "col-span-4 md:aspect-5/3",
    sizes: "(min-width: 1520px) 453px, 33vw",
    revealDelay: 100,
  },
  {
    src: "/assets/images/life/life14.jpg",
    alt: "Uczestnicy spotkania Hoodmood podczas świątecznej imprezy",
    className: "col-span-3",
    sizes: "(min-width: 1520px) 453px, 33vw",
    revealDelay: 0,
  },
  {
    src: "/assets/images/life/life15.jpg",
    alt: "Trójka uczestników Hoodmood w kaskach przed trasą parku linowego",
    className: "col-span-3",
    sizes: "(min-width: 1520px) 453px, 33vw",
    revealDelay: 0,
  },
  {
    src: "/assets/images/life/life16.jpg",
    alt: "Grupa Hoodmood pozuje w lustrzanej kuli przed londyńskim Westminsterem",
    className: "col-span-2",
    sizes: "(min-width: 1520px) 453px, 33vw",
    revealDelay: 200,
  },
  {
    src: "/assets/images/life/life17.jpg",
    alt: "Duże wydarzenie plenerowe z publicznością, sceną i występem",
    className: "col-span-8 md:aspect-5/3",
    sizes: "(min-width: 1520px) 453px, 33vw",
    revealDelay: 100,
  },
  {
    src: "/assets/images/life/life18.jpg",
    alt: "Grupa Hoodmood na karuzeli w parku rozrywki",
    className: "col-span-4",
    sizes: "(min-width: 1520px) 453px, 33vw",
    revealDelay: 200,
  },
];
